version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    container_name: angular_symfony
    ports:
      - "4250:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network    
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: symfony_symfony
    ports:
      - "8050:8080"        
    networks:
      - app-network
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://usuario:password@db:5432/symfony_base_datos

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=symfony_base_datos
      - POSTGRES_USER=usuario
      - POSTGRES_PASSWORD=password
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
